///////////////////////////////////////////////////////////
//  Faltas.cs
//  Implementation of the Class Faltas
//  Generated by Enterprise Architect
//  Created on:      16-ago-2014 2:45:24
//  Original author: Intel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidades.GestionAsistencia
{
    public class Faltas
    {

        private DateTime fecha;
        private string idFaltas;
        private bool justificacion;
        private string idCalendario;
        private string cedula;



        ~Faltas()
        {

        }

        public virtual void Dispose()
        {

        }

        public Faltas()
        {

        }

        /// 
        /// <param name="justificacion"></param>
        /// <param name="fecha"></param>
        /// <param name="idfaltas"></param>
        public Faltas(bool justificacion, DateTime fecha, string idfaltas, string idCalendario, string cedula)
        {
            IdFaltas = idFaltas;
            Fecha = fecha;
            Justificacion = justificacion;
            IdCalendario = idCalendario;
            Cedula = cedula;
        }

        public DateTime Fecha
        {
            get
            {
                return fecha;
            }
            set
            {
                fecha = value;
            }
        }

        public string IdFaltas
        {
            get
            {
                return idFaltas;
            }
            set
            {
                idFaltas = value;
            }
        }

        public bool Justificacion
        {
            get
            {
                return justificacion;
            }
            set
            {
                justificacion = value;
            }
        }
        public string IdCalendario
        {
            get { return idCalendario; }
            set { idCalendario = value; }
        }
        public string Cedula
        {
            get { return cedula; }
            set { cedula = value; }
        }

    }
}//end Faltas