///////////////////////////////////////////////////////////
//  Imprevistos.cs
//  Implementation of the Class Imprevistos
//  Generated by Enterprise Architect
//  Created on:      16-ago-2014 2:45:24
//  Original author: JORGE-TORRES
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidades.GestionAsistencia
{

    public class Imprevistos
    {

        private string descripcion;
        private DateTime fechaFinal;
        private DateTime fechaInicio;
        private string idImprevisto;



        ~Imprevistos()
        {

        }

        public virtual void Dispose()
        {

        }

        public Imprevistos()
        {

        }

        /// 
        /// <param name="idimprevisto"></param>
        /// <param name="fechainicio"></param>
        /// <param name="fechafinal"></param>
        /// <param name="descripcion"></param>
        public Imprevistos(string idimprevisto, DateTime fechainicio, DateTime fechafinal, string descripcion)
        {

        }

        public string Descripcion
        {
            get
            {
                return descripcion;
            }
            set
            {
                descripcion = value;
            }
        }

        public DateTime FechaFinal
        {
            get
            {
                return fechaFinal;
            }
            set
            {
                fechaFinal = value;
            }
        }

        public DateTime FechaInicio
        {
            get
            {
                return fechaInicio;
            }
            set
            {
                fechaInicio = value;
            }
        }

        public string IdImprevisto
        {
            get
            {
                return idImprevisto;
            }
            set
            {
                idImprevisto = value;
            }
        }

    }
}//end Imprevistos