///////////////////////////////////////////////////////////
//  Huella.cs
//  Implementation of the Class Huella
//  Generated by Enterprise Architect
//  Created on:      16-ago-2014 2:45:24
//  Original author: Intel
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidades.GestionPersonal
{

    public class Huella
    {

        private byte[] dataHuella1;
        private byte[] dataHuella2;
        private string idHuella;
        private string cedula;

        ~Huella()
        {

        }

        public virtual void Dispose()
        {

        }

        public Huella()
        {

        }

        /// 
        /// <param name="datahuella1"></param>
        /// <param name="datahuella2"></param>
        /// <param name="idHuella"></param>
        public Huella(byte[] datahuella1, byte[] datahuella2, string idHuella, string cedula)
        {
            DataHuella1 = datahuella1;
            DataHuella2 = datahuella2;
            IdHuella = idHuella;
            Cedula = cedula;
        }

        public byte[] DataHuella1
        {
            get
            {
                return dataHuella1;
            }
            set
            {
                dataHuella1 = value;
            }
        }

        public byte[] DataHuella2
        {
            get
            {
                return dataHuella2;
            }
            set
            {
                dataHuella2 = value;
            }
        }

        public string IdHuella
        {
            get
            {
                return idHuella;
            }
            set
            {
                idHuella = value;
            }
        }

        public string Cedula
        {
            get { return cedula; }
            set { cedula = value; }
        }

    }
}//end Huella