///////////////////////////////////////////////////////////
//  Personal.cs
//  Implementation of the Class Personal
//  Generated by Enterprise Architect
//  Created on:      16-ago-2014 2:45:24
//  Original author: Intel
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace CapaEntidades.GestionPersonal
{

        public enum Sexo { Hombre, Mujer }
        public enum Tipo { DocenteContratado, DocenteNombremiento, Administrativo, Servicio }


    public class Personal
    {


        private string apellido;
        private string cargo;
        private string cedula;
        private string ciudad;
        private string correo;
        private string direccion;
        private string nombre;
        private char sexo;
        private string telefono;
        private string tipo;
        private string titulo;
        private byte[] dataFoto;

        /// <summary>
        /// ////////////////////////////77que es esto
        /// </summary>
        //public Huella m_Huella;
        //public Faltas m_Faltas;
        //public Asistencia m_Asistencia;
        //public Calendario m_Calendario;
        //public Imprevistos m_Imprevistos;



        ~Personal()
        {

        }

        public virtual void Dispose()
        {

        }

        public Personal()
        {

        }

        /// 
        /// <param name="foto"></param>
        /// <param name="tipo"></param>
        /// <param name="titulo"></param>
        /// <param name="telefono"></param>
        /// <param name="sexo"></param>
        /// <param name="nombre"></param>
        /// <param name="direccion"></param>
        /// <param name="correo"></param>
        /// <param name="ciudad"></param>
        /// <param name="cedula"></param>
        /// <param name="cargo"></param>
        /// <param name="apellido"></param>
        public Personal(byte foto, string tipo, string titulo, string telefono, char sexo, string nombre, string direccion, string correo, string ciudad, string cedula, string cargo, string apellido)
        {

        }

        public string Apellido
        {
            get
            {
                return apellido;
            }
            set
            {
                apellido = value;
            }
        }

        public string Cargo
        {
            get
            {
                return cargo;
            }
            set
            {
                cargo = value;
            }
        }

        public string Cedula
        {
            get
            {
                return cedula;
            }
            set
            {
                cedula = value;
            }
        }

        public string Ciudad
        {
            get
            {
                return ciudad;
            }
            set
            {
                ciudad = value;
            }
        }

        public string Correo
        {
            get
            {
                return correo;
            }
            set
            {
                correo = value;
            }
        }

        public byte[] DataFoto
        {
            get
            {
                return dataFoto;
            }
            set
            {
                dataFoto = value;
            }
        }

        public string Direccion
        {
            get
            {
                return direccion;
            }
            set
            {
                direccion = value;
            }
        }

        public string Nombre
        {
            get
            {
                return nombre;
            }
            set
            {
                nombre = value;
            }
        }

        public char Sexo
        {
            get
            {
                return sexo;
            }
            set
            {
                sexo = value;
            }
        }

        public string Telefono
        {
            get
            {
                return telefono;
            }
            set
            {
                telefono = value;
            }
        }

        public string Tipo
        {
            get
            {
                return tipo;
            }
            set
            {
                tipo = value;
            }
        }

        public string Titulo
        {
            get
            {
                return titulo;
            }
            set
            {
                titulo = value;
            }
        }
    }
}//end Personal