///////////////////////////////////////////////////////////
//  Ayuda.cs
//  Implementation of the Class Ayuda
//  Generated by Enterprise Architect
//  Created on:      16-ago-2014 2:45:23
//  Original author: Jorge
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidades.GestionAyuda
{


    public class Ayuda
    {

        private byte[] archivo;
        private int idAyuda;
        private string nombre;



        ~Ayuda()
        {

        }

        public virtual void Dispose()
        {

        }

        public Ayuda()
        {

        }

        /// 
        /// <param name="idAyuda"></param>
        /// <param name="archivo"></param>
        /// <param name="nombre"></param>
        public Ayuda(int idAyuda, byte[] archivo, string nombre)
        {

        }

        public byte[] Archivo
        {
            get
            {
                return archivo;
            }
            set
            {
                archivo = value;
            }
        }

        public int IdAyuda
        {
            get
            {
                return idAyuda;
            }
            set
            {
                idAyuda = value;
            }
        }

        public string Nombre
        {
            get
            {
                return nombre;
            }
            set
            {
                nombre = value;
            }
        }

    }
}//end Ayuda