///////////////////////////////////////////////////////////
//  Permisos.cs
//  Implementation of the Class Permisos
//  Generated by Enterprise Architect
//  Created on:      16-ago-2014 2:45:24
//  Original author: JORGE-TORRES
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidades.GestionSeguridad
{



    public class Permisos
    {

        private bool busqueda;
        private bool eliminacion;
        private bool escritura;
        private bool estado;
        private string idPermiso;
        private bool lectura;
        private bool modificacion;
        private string idRol;
        private string idRecurso;

        



        ~Permisos()
        {

        }

        public virtual void Dispose()
        {

        }

        public Permisos()
        {

        }

        /// 
        /// <param name="idPermiso"></param>
        /// <param name="estado"></param>
        /// <param name="busqueda"></param>
        /// <param name="eliminacion"></param>
        /// <param name="escritura"></param>
        /// <param name="lectura"></param>
        /// <param name="modificacion"></param>
        public Permisos(string idPermiso, bool estado, bool busqueda, bool eliminacion, bool escritura, bool lectura, bool modificacion, string idRol, string idRecurso)
        {
            IdPermiso = idPermiso;
            Estado = estado;
            Busqueda = busqueda;
            Eliminacion = eliminacion;
            Escritura = escritura;
            Lectura = lectura;
            Modificacion = modificacion;
            IdRol = idRol;
            IdRecurso = idRecurso;
        }

        public bool Busqueda
        {
            get
            {
                return busqueda;
            }
            set
            {
                busqueda = value;
            }
        }

        public bool Eliminacion
        {
            get
            {
                return eliminacion;
            }
            set
            {
                eliminacion = value;
            }
        }

        public bool Escritura
        {
            get
            {
                return escritura;
            }
            set
            {
                escritura = value;
            }
        }

        public bool Estado
        {
            get
            {
                return estado;
            }
            set
            {
                estado = value;
            }
        }

        public string IdPermiso
        {
            get
            {
                return idPermiso;
            }
            set
            {
                idPermiso = value;
            }
        }

        public bool Lectura
        {
            get
            {
                return lectura;
            }
            set
            {
                lectura = value;
            }
        }

        public bool Modificacion
        {
            get
            {
                return modificacion;
            }
            set
            {
                modificacion = value;
            }
        }
        public string IdRol
        {
            get { return idRol; }
            set { idRol = value; }
        }
        public string IdRecurso
        {
            get { return idRecurso; }
            set { idRecurso = value; }
        }

    }
}//end Permisos