///////////////////////////////////////////////////////////
//  Recurso.cs
//  Implementation of the Class Recurso
//  Generated by Enterprise Architect
//  Created on:      16-ago-2014 2:45:24
//  Original author: tania-jeff
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidades.GestionSeguridad{



    public class Recurso
    {

        private string descripcion;
        private bool estado;
        private bool habilitadoMenu;
        private string idRecurso;
        private string nombre;
        private int posicionMenu;
        private string urlRecurso;
        private string idModulo;





        ~Recurso()
        {

        }

        public virtual void Dispose()
        {

        }

        public Recurso()
        {

        }

        /// 
        /// <param name="urlRecurso"></param>
        /// <param name="posicionMenu"></param>
        /// <param name="nombre"></param>
        /// <param name="idRecurso"></param>
        /// <param name="habilitadoMenu"></param>
        /// <param name="estado"></param>
        /// <param name="descripcion"></param>
        public Recurso(string urlRecurso, int posicionMenu, string nombre, string idRecurso, bool habilitadoMenu, bool estado, string descripcion, string idModulo)
        {
            UrlRecurso = urlRecurso;
            PosicionMenu = posicionMenu;
            Nombre = nombre;
            IdRecurso = idRecurso;
            HabilitadoMenu = habilitadoMenu;
            Estado = estado;
            Descripcion = descripcion;
            IdModulo = idModulo;
        }

        public string Descripcion
        {
            get
            {
                return descripcion;
            }
            set
            {
                descripcion = value;
            }
        }

        public bool Estado
        {
            get
            {
                return estado;
            }
            set
            {
                estado = value;
            }
        }

        public bool HabilitadoMenu
        {
            get
            {
                return habilitadoMenu;
            }
            set
            {
                habilitadoMenu = value;
            }
        }

        public string IdRecurso
        {
            get
            {
                return idRecurso;
            }
            set
            {
                idRecurso = value;
            }
        }

        public string Nombre
        {
            get
            {
                return nombre;
            }
            set
            {
                nombre = value;
            }
        }

        public int PosicionMenu
        {
            get
            {
                return posicionMenu;
            }
            set
            {
                posicionMenu = value;
            }
        }

        public string UrlRecurso
        {
            get
            {
                return urlRecurso;
            }
            set
            {
                urlRecurso = value;
            }
        }
        public string IdModulo{
           get { return idModulo; }
           set { idModulo = value; }
        }

    }
}//end Recurso