///////////////////////////////////////////////////////////
//  Roles.cs
//  Implementation of the Class Roles
//  Generated by Enterprise Architect
//  Created on:      16-ago-2014 2:45:24
//  Original author: JORGE-TORRES
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidades.GestionSeguridad
{



    public class Roles
    {

        private string descripcion;
        private bool estado;
        private string idRol;
        private string nombre;
        public Permisos m_Permisos;



        ~Roles()
        {

        }

        public virtual void Dispose()
        {

        }

        public Roles()
        {

        }

        /// 
        /// <param name="idrol"></param>
        /// <param name="nombre"></param>
        /// <param name="descripcion"></param>
        /// <param name="estado"></param>
        public Roles(string idrol, string nombre, string descripcion, bool estado)
        {

        }

        public string Descripcion
        {
            get
            {
                return descripcion;
            }
            set
            {
                descripcion = value;
            }
        }

        public bool Estado
        {
            get
            {
                return estado;
            }
            set
            {
                estado = value;
            }
        }

        public string IdRol
        {
            get
            {
                return idRol;
            }
            set
            {
                idRol = value;
            }
        }

        public string Nombre
        {
            get
            {
                return nombre;
            }
            set
            {
                nombre = value;
            }
        }

    }
}//end Roles