///////////////////////////////////////////////////////////
//  Calendario.cs
//  Implementation of the Class Calendario
//  Generated by Enterprise Architect
//  Created on:      16-ago-2014 2:45:23
//  Original author: JORGE-TORRES
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidades.GestionPlanificacion
{

    public class Calendario
    {

        private string descripcion;
        private DateTime fechaFin;
        private DateTime fechaInicio;
        private string idCalendario;
        private string nombre;
        public DiasNoLaborables m_DiasNoLaborables;
        public DiasAdicionales m_DiasAdicionales;



        ~Calendario()
        {

        }

        public virtual void Dispose()
        {

        }

        public Calendario()
        {

        }

        /// 
        /// <param name="nombre"></param>
        /// <param name="descripcion"></param>
        /// <param name="idCalendario"></param>
        /// <param name="fechafin"></param>
        /// <param name="fechainicio"></param>
        public Calendario(string nombre, string descripcion, string idCalendario, DateTime fechafin, DateTime fechainicio)
        {

        }

        public string Descripcion
        {
            get
            {
                return descripcion;
            }
            set
            {
                descripcion = value;
            }
        }

        public DateTime FechaFin
        {
            get
            {
                return fechaFin;
            }
            set
            {
                fechaFin = value;
            }
        }

        public DateTime FechaInicio
        {
            get
            {
                return fechaInicio;
            }
            set
            {
                fechaInicio = value;
            }
        }

        public string IdCalendario
        {
            get
            {
                return idCalendario;
            }
            set
            {
                idCalendario = value;
            }
        }

        public string Nombre
        {
            get
            {
                return nombre;
            }
            set
            {
                nombre = value;
            }
        }

    }
}//end Calendario