///////////////////////////////////////////////////////////
//  DiasAdicionales.cs
//  Implementation of the Class DiasAdicionales
//  Generated by Enterprise Architect
//  Created on:      16-ago-2014 2:45:24
//  Original author: Intel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidades.GestionPlanificacion
{


    public class DiasAdicionales
    {

        private string descripcion;
        private DateTime fecha;
        private string idDiasAdcionales;
        private string idCalendario;

        ~DiasAdicionales()
        {

        }

        public virtual void Dispose()
        {

        }

        public DiasAdicionales()
        {

        }

        /// 
        /// <param name="idadicionales"></param>
        /// <param name="fecha"></param>
        /// <param name="descripcion"></param>
        public DiasAdicionales(string idDiasAdicionales, DateTime fecha, string descripcion,  string idCalendario)
        {
            IdDiasAdcionales = idDiasAdicionales;
            Fecha = fecha;
            Descripcion = descripcion;
            IdCalendario = idCalendario;
            
        }

        public string Descripcion
        {
            get
            {
                return descripcion;
            }
            set
            {
                descripcion = value;
            }
        }

        public DateTime Fecha
        {
            get
            {
                return fecha;
            }
            set
            {
                fecha = value;
            }
        }

        public string IdDiasAdcionales
        {
            get
            {
                return idDiasAdcionales;
            }
            set
            {
                idDiasAdcionales = value;
            }
        }
        public string IdCalendario
        {
            get { return idCalendario; }
            set { idCalendario = value; }
        }
    }
}//end DiasAdicionales