///////////////////////////////////////////////////////////
//  DiasNoLaborables.cs
//  Implementation of the Class DiasNoLaborables
//  Generated by Enterprise Architect
//  Created on:      16-ago-2014 2:45:24
//  Original author: Intel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidades.GestionPlanificacion
{


    public class DiasNoLaborables
    {

        private string descripcion;
        private DateTime fecha;
        private string idDiasNoLaborables;
        private string idCalendario;



        ~DiasNoLaborables()
        {

        }

        public virtual void Dispose()
        {

        }

        public DiasNoLaborables()
        {

        }

        /// 
        /// <param name="idnolaborables"></param>
        /// <param name="fecha"></param>
        /// <param name="descripcion"></param>
        public DiasNoLaborables(string idDiasNoLaborables, DateTime fecha, string descripcion, string idCalendario)
        {
            IdDiasNoLaborables = idDiasNoLaborables;
            Fecha = fecha;
            Descripcion = descripcion;
            IdCalendario = idCalendario;
            
        }

        public string Descripcion
        {
            get
            {
                return descripcion;
            }
            set
            {
                descripcion = value;
            }
        }

        public DateTime Fecha
        {
            get
            {
                return fecha;
            }
            set
            {
                fecha = value;
            }
        }

        public string IdDiasNoLaborables
        {
            get
            {
                return idDiasNoLaborables;
            }
            set
            {
                idDiasNoLaborables = value;
            }
        }
        public string IdCalendario
        {
            get { return idCalendario; }
            set { idCalendario = value; }
        }
    }
}//end DiasNoLaborables